/**
 * Output formatters for different output formats (text, JSON, markdown)
 */
import type {
  ReviewOutput,
  StructuredReview,
  ReviewIssue,
  FormatterOptions,
  IssueCounts,
  Severity,
} from './types.js'
import { countIssuesBySeverity } from './parser.js'

/**
 * Severity icons for visual formatting
 */
const SEVERITY_ICONS: Record<Severity, string> = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🔵',
}

/**
 * Format review output as plain text
 */
export function formatAsText(
  review: ReviewOutput,
  _options?: FormatterOptions
): string {
  // If no structured data, return raw content
  if (!review.structured) {
    return review.raw
  }

  // For text format, the raw markdown is already readable
  return review.raw
}

/**
 * Format review output as JSON
 */
export function formatAsJson(
  review: ReviewOutput,
  options?: FormatterOptions
): string {
  const output: Record<string, unknown> = {}

  if (review.structured) {
    const structured = review.structured

    output.summary = structured.summary
    output.issues = structured.issues
    output.issueCount = countIssuesBySeverity(structured.issues)
    output.positives = structured.positives
    output.verdict = structured.verdict

    if (options?.includeMetadata !== false) {
      output.metadata = structured.metadata
    }
  } else {
    // Fallback when structured parsing failed
    output.summary = null
    output.issues = []
    output.issueCount = { critical: 0, high: 0, medium: 0, low: 0 }
    output.positives = []
    output.verdict = null
    output.parseError = true
  }

  if (options?.includeRaw) {
    output.raw = review.raw
  }

  return JSON.stringify(output, null, 2)
}

/**
 * Format review output as markdown report
 */
export function formatAsMarkdown(
  review: ReviewOutput,
  options?: FormatterOptions
): string {
  // If no structured data, return raw content with header
  if (!review.structured) {
    return `# Code Review Report\n\n${review.raw}`
  }

  const structured = review.structured
  const parts: string[] = []

  // Header
  parts.push('# Code Review Report')
  parts.push('')

  // Metadata
  if (options?.includeMetadata !== false && structured.metadata) {
    const meta = structured.metadata
    parts.push(`**Generated:** ${meta.timestamp}`)
    if (meta.scope) {
      parts.push(`**Scope:** ${formatScope(meta)}`)
    }
    if (meta.model) {
      parts.push(`**Model:** ${meta.model}`)
    }
    if (meta.agentic) {
      parts.push(`**Mode:** Agentic review${meta.toolCalls ? ` (${meta.toolCalls} tool calls)` : ''}`)
    }
    parts.push('')
  }

  // Summary
  parts.push('## Summary')
  parts.push('')
  parts.push(structured.summary)
  parts.push('')

  // Issues
  const issueCounts = countIssuesBySeverity(structured.issues)
  const totalIssues = Object.values(issueCounts).reduce((a, b) => a + b, 0)

  parts.push(`## Issues Found (${totalIssues})`)
  parts.push('')

  if (structured.issues.length === 0) {
    parts.push('No issues found.')
    parts.push('')
  } else {
    // Add issue summary badge
    parts.push(formatIssueBadges(issueCounts))
    parts.push('')

    // Group and display issues by severity
    const severityOrder: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']
    for (const severity of severityOrder) {
      const issuesForSeverity = structured.issues.filter(i => i.severity === severity)
      if (issuesForSeverity.length > 0) {
        for (const issue of issuesForSeverity) {
          parts.push(formatIssueMarkdown(issue, options?.verbose))
          parts.push('')
        }
      }
    }
  }

  // Positive observations
  if (structured.positives.length > 0) {
    parts.push('## Positive Observations')
    parts.push('')
    for (const positive of structured.positives) {
      parts.push(`- ${positive}`)
    }
    parts.push('')
  }

  // Verdict
  parts.push('## Verdict')
  parts.push('')
  parts.push(formatVerdictMarkdown(structured.verdict, issueCounts))
  parts.push('')

  // Footer
  parts.push('---')
  parts.push('*Generated by [kode-review](https://github.com/kofikode/kode-review-cli)*')

  return parts.join('\n')
}

/**
 * Format scope for display
 */
function formatScope(meta: StructuredReview['metadata']): string {
  const parts: string[] = []

  if (meta.scope === 'pr' || meta.scope === 'both') {
    if (meta.prNumber) {
      parts.push(`PR #${meta.prNumber}`)
    } else if (meta.mrIid) {
      parts.push(`MR !${meta.mrIid}`)
    } else {
      parts.push('PR/MR')
    }
  }

  if (meta.scope === 'local' || meta.scope === 'both') {
    parts.push('Local changes')
  }

  if (meta.branch) {
    parts.push(`on \`${meta.branch}\``)
  }

  return parts.join(' ') || meta.scope
}

/**
 * Format issue counts as badges
 */
function formatIssueBadges(counts: IssueCounts): string {
  const badges: string[] = []

  if (counts.critical > 0) {
    badges.push(`🔴 ${counts.critical} Critical`)
  }
  if (counts.high > 0) {
    badges.push(`🟠 ${counts.high} High`)
  }
  if (counts.medium > 0) {
    badges.push(`🟡 ${counts.medium} Medium`)
  }
  if (counts.low > 0) {
    badges.push(`🔵 ${counts.low} Low`)
  }

  return badges.join(' | ')
}

/**
 * Format a single issue as markdown
 */
function formatIssueMarkdown(issue: ReviewIssue, verbose?: boolean): string {
  const parts: string[] = []
  const icon = SEVERITY_ICONS[issue.severity]

  // Header
  parts.push(`### ${icon} ${issue.severity}: ${issue.title}`)
  parts.push('')

  // Category and location
  if (issue.category) {
    parts.push(`**Category:** ${issue.category}`)
  }

  if (issue.file) {
    const location = issue.line
      ? issue.endLine
        ? `${issue.file}:${issue.line}-${issue.endLine}`
        : `${issue.file}:${issue.line}`
      : issue.file
    parts.push(`**Location:** \`${location}\``)
  }

  parts.push(`**Confidence:** ${issue.confidence}`)
  parts.push('')

  // Description
  parts.push(issue.description)
  parts.push('')

  // Code snippets (only in verbose mode or for high-severity issues)
  if (verbose || issue.severity === 'CRITICAL' || issue.severity === 'HIGH') {
    if (issue.codeSnippet) {
      parts.push('**Problematic code:**')
      parts.push('```')
      parts.push(issue.codeSnippet)
      parts.push('```')
      parts.push('')
    }

    if (issue.suggestion) {
      parts.push('**Suggested fix:**')
      parts.push('```')
      parts.push(issue.suggestion)
      parts.push('```')
      parts.push('')
    }
  }

  return parts.join('\n')
}

/**
 * Format verdict section as markdown
 */
function formatVerdictMarkdown(
  verdict: StructuredReview['verdict'],
  issueCounts: IssueCounts
): string {
  const parts: string[] = []

  // Recommendation with visual indicator
  const recIndicator =
    verdict.recommendation === 'APPROVE'
      ? '✅'
      : verdict.recommendation === 'REQUEST_CHANGES'
      ? '❌'
      : '⚠️'

  parts.push(`**Recommendation:** ${recIndicator} ${verdict.recommendation}`)
  parts.push('')

  // Merge decision
  const mergeIndicator =
    verdict.mergeDecision === 'SAFE_TO_MERGE'
      ? '🟢'
      : verdict.mergeDecision === 'DO_NOT_MERGE'
      ? '🔴'
      : '🟡'

  parts.push(`**Merge Decision:** ${mergeIndicator} ${verdict.mergeDecision.replace(/_/g, ' ')}`)
  parts.push('')

  // Confidence
  parts.push(`**Confidence:** ${verdict.confidence}`)
  parts.push('')

  // Rationale
  if (verdict.rationale) {
    parts.push(`**Rationale:** ${verdict.rationale}`)
    parts.push('')
  }

  // Issue summary
  parts.push('**Issues Summary:**')
  parts.push(`- ${issueCounts.critical} Critical`)
  parts.push(`- ${issueCounts.high} High`)
  parts.push(`- ${issueCounts.medium} Medium`)
  parts.push(`- ${issueCounts.low} Low`)

  return parts.join('\n')
}

/**
 * Format review for posting as a PR/MR comment
 * This is a more compact format suitable for VCS platforms
 */
export function formatForPRComment(
  review: StructuredReview,
  options?: { maxLength?: number }
): string {
  const maxLength = options?.maxLength ?? 65535 // GitHub comment limit

  const parts: string[] = []

  // Header
  parts.push('## 🤖 Automated Code Review')
  parts.push('')

  // Summary
  parts.push(`### Summary`)
  parts.push(review.summary)
  parts.push('')

  // Issue summary badge
  const issueCounts = countIssuesBySeverity(review.issues)
  parts.push(formatIssueBadges(issueCounts))
  parts.push('')

  // Issues - abbreviated for comments
  if (review.issues.length > 0) {
    parts.push('<details>')
    parts.push('<summary>📋 Issues Found</summary>')
    parts.push('')

    const severityOrder: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']
    for (const severity of severityOrder) {
      const issuesForSeverity = review.issues.filter(i => i.severity === severity)
      for (const issue of issuesForSeverity) {
        const icon = SEVERITY_ICONS[severity]
        const location = issue.file
          ? issue.line
            ? `\`${issue.file}:${issue.line}\``
            : `\`${issue.file}\``
          : ''

        parts.push(`**${icon} ${severity}:** ${issue.title}`)
        if (location) {
          parts.push(`  - ${location}`)
        }
        parts.push('')
      }
    }

    parts.push('</details>')
    parts.push('')
  }

  // Verdict
  const recIndicator =
    review.verdict.recommendation === 'APPROVE'
      ? '✅'
      : review.verdict.recommendation === 'REQUEST_CHANGES'
      ? '❌'
      : '⚠️'

  parts.push(`### Verdict: ${recIndicator} ${review.verdict.recommendation.replace(/_/g, ' ')}`)
  parts.push('')

  if (review.verdict.rationale) {
    parts.push(review.verdict.rationale)
    parts.push('')
  }

  // Footer
  parts.push('---')
  parts.push('*Generated by [kode-review](https://github.com/kofikode/kode-review-cli)*')

  let result = parts.join('\n')

  // Truncate if needed
  if (result.length > maxLength) {
    const truncateNote = '\n\n... (truncated - see full report in CI logs)'
    result = result.substring(0, maxLength - truncateNote.length) + truncateNote
  }

  return result
}
