/**
 * Pre-commit hook generator for code review
 */
import { writeFile, readFile, access, mkdir, chmod } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { constants } from 'node:fs'
import { confirm, select } from '@inquirer/prompts'
import { logger } from '../utils/logger.js'
import { isGitRepository, getRepoRoot } from '../vcs/detect.js'
import type { OutputFormat } from '../output/types.js'

export type HookType = 'pre-commit' | 'pre-push'
export type HookScope = 'staged' | 'local'

export interface InitHooksOptions {
  hookType?: HookType
  scope?: HookScope
  format?: OutputFormat
  failOnIssues?: boolean
  interactive?: boolean
}

const PRE_COMMIT_HOOK_TEMPLATE = `#!/bin/sh
# Kode-Review pre-commit hook
# Generated by: kode-review --init-hooks
#
# This hook runs code review on staged changes before commit.
# Exit code 0 = allow commit, non-zero = block commit

# Run code review on staged changes
kode-review --scope local --format {{FORMAT}} --quiet

# Exit with review exit code
exit $?
`

const PRE_PUSH_HOOK_TEMPLATE = `#!/bin/sh
# Kode-Review pre-push hook
# Generated by: kode-review --init-hooks
#
# This hook runs code review on local changes before push.
# Exit code 0 = allow push, non-zero = block push

# Run code review on local changes
kode-review --scope local --format {{FORMAT}} --quiet

# Exit with review exit code
exit $?
`

const HUSKY_PRE_COMMIT_TEMPLATE = `#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Kode-Review pre-commit hook
# Generated by: kode-review --init-hooks

kode-review --scope local --format {{FORMAT}} --quiet
`

/**
 * Initialize git hooks for code review
 */
export async function initHooks(options?: InitHooksOptions): Promise<void> {
  const {
    hookType = 'pre-commit',
    format = 'text',
    interactive = true,
  } = options ?? {}

  // Verify we're in a git repository
  if (!(await isGitRepository())) {
    throw new Error('Not in a git repository. Please run this command from within a git repository.')
  }

  const repoRoot = await getRepoRoot()
  if (!repoRoot) {
    throw new Error('Could not determine repository root.')
  }

  // Detect Husky
  const huskyDir = join(repoRoot, '.husky')
  const hasHusky = await fileExists(join(huskyDir, '_', 'husky.sh'))

  // Determine hook location
  let hookPath: string
  let hookContent: string

  if (hasHusky) {
    hookPath = join(huskyDir, hookType)
    hookContent = generateHuskyHookContent(hookType, format)
    logger.info('Husky detected - generating Husky-compatible hook')
  } else {
    const gitDir = join(repoRoot, '.git', 'hooks')
    hookPath = join(gitDir, hookType)
    hookContent = generateGitHookContent(hookType, format)
  }

  // Check if hook already exists
  const hookExists = await fileExists(hookPath)

  if (hookExists) {
    const existingContent = await readFile(hookPath, 'utf-8')

    // Check if it's already a kode-review hook
    if (existingContent.includes('kode-review')) {
      if (interactive) {
        const replace = await confirm({
          message: `A kode-review ${hookType} hook already exists. Replace it?`,
          default: false,
        })

        if (!replace) {
          logger.info('Hook generation cancelled.')
          return
        }
      } else {
        logger.warn(`Replacing existing kode-review ${hookType} hook.`)
      }
    } else {
      // Existing non-kode-review hook
      if (interactive) {
        const action = await select({
          message: `A ${hookType} hook already exists. What would you like to do?`,
          choices: [
            { name: 'Append kode-review to existing hook', value: 'append' },
            { name: 'Replace existing hook entirely', value: 'replace' },
            { name: 'Cancel', value: 'cancel' },
          ],
        })

        if (action === 'cancel') {
          logger.info('Hook generation cancelled.')
          return
        }

        if (action === 'append') {
          hookContent = appendToExistingHook(existingContent, hookType, format)
        }
      } else {
        logger.warn(`Existing ${hookType} hook found. Use interactive mode to choose action.`)
        return
      }
    }
  }

  // Ensure hooks directory exists
  const hooksDir = dirname(hookPath)
  await mkdir(hooksDir, { recursive: true })

  // Write the hook
  await writeFile(hookPath, hookContent, 'utf-8')

  // Make executable
  await chmod(hookPath, 0o755)

  logger.success(`${hookType} hook created at ${hookPath}`)

  console.log('')
  console.log('Hook will run kode-review before each commit.')
  console.log('To skip the hook temporarily, use: git commit --no-verify')
  console.log('')

  if (hasHusky) {
    console.log('Note: Since you use Husky, you may need to run:')
    console.log('  npx husky add .husky/pre-commit "kode-review --scope local --quiet"')
    console.log('')
  }
}

/**
 * Generate standard git hook content
 */
function generateGitHookContent(hookType: HookType, format: OutputFormat): string {
  const template = hookType === 'pre-commit'
    ? PRE_COMMIT_HOOK_TEMPLATE
    : PRE_PUSH_HOOK_TEMPLATE

  return template.replace(/{{FORMAT}}/g, format)
}

/**
 * Generate Husky-compatible hook content
 */
function generateHuskyHookContent(_hookType: HookType, format: OutputFormat): string {
  // Note: Currently only pre-commit template exists for Husky
  // Future enhancement: Add pre-push template for Husky
  return HUSKY_PRE_COMMIT_TEMPLATE.replace(/{{FORMAT}}/g, format)
}

/**
 * Append kode-review to an existing hook
 */
function appendToExistingHook(
  existingContent: string,
  _hookType: HookType, // eslint-disable-line @typescript-eslint/no-unused-vars
  format: OutputFormat
): string {
  const appendContent = `

# Kode-Review integration (added by kode-review --init-hooks)
kode-review --scope local --format ${format} --quiet
KODE_REVIEW_EXIT=$?
if [ $KODE_REVIEW_EXIT -ne 0 ]; then
  echo "Code review found issues. Commit blocked."
  exit $KODE_REVIEW_EXIT
fi
`

  return existingContent.trimEnd() + appendContent
}

/**
 * Check if a file exists
 */
async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK)
    return true
  } catch {
    return false
  }
}

/**
 * Remove kode-review hooks
 */
export async function removeHooks(hookType: HookType = 'pre-commit'): Promise<void> {
  if (!(await isGitRepository())) {
    throw new Error('Not in a git repository.')
  }

  const repoRoot = await getRepoRoot()
  if (!repoRoot) {
    throw new Error('Could not determine repository root.')
  }

  // Check both standard git hooks and Husky
  const hookPaths = [
    join(repoRoot, '.git', 'hooks', hookType),
    join(repoRoot, '.husky', hookType),
  ]

  for (const hookPath of hookPaths) {
    if (await fileExists(hookPath)) {
      const content = await readFile(hookPath, 'utf-8')

      if (content.includes('kode-review')) {
        // If it's purely a kode-review hook, we could delete it
        // For safety, just warn the user
        logger.info(`Found kode-review hook at ${hookPath}`)
        logger.info('To remove, delete or edit the file manually.')
      }
    }
  }
}
